AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  Exclude:
    - "docs/**/*"
    - "workspace/**/*"
    - "extensions/**/*"
Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: true

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 50

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/IfInsideElse:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/WordArray:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Layout/SpaceAroundOperators:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/RedundantBegin:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
