# change to a node accordingly
export OPSCODE_USER="hoatle"
export OPSCODE_ORGNAME="teracy"
export KNIFE_CLIENT_KEY_FOLDER="$HOME/.chef"
export KNIFE_VALIDATION_KEY_FOLDER="$HOME/.chef"
export KNIFE_CHEF_SERVER="https://api.opscode.com/organizations/$OPSCODE_ORGNAME"
export KNIFE_CACHE_PATH="$HOME/.chef/checksums"
export KNIFE_COOKBOOK_COPYRIGHT="Teracy, Inc."
export KNIFE_COOKBOOK_LICENSE="BSD"
export KNIFE_COOKBOOK_EMAIL="devops@teracy.com"
