ARG PYTHON_VERSION=3.7

FROM python:$PYTHON_VERSION

RUN mkdir -p /opt/app

ENV TERM=xterm-256color APP=/opt/app

# buggy: https://github.com/GoogleContainerTools/skaffold/issues/1721
# WORKDIR $APP

ADD requirements.txt $APP/

RUN cd $APP && pip install -r requirements.txt

ADD . $APP
