version: "3"

services:

  ngrok-dev:
    image: ${NGROK_DEV_IMAGE:-wernight/ngrok}
    command: ngrok http -host-header=dev.dev-docs.teracy.dev nginx-proxy:80
    environment:
      - VIRTUAL_HOST=ngrok-dev.dev-docs.teracy.dev
      - HTTPS_METHOD=noredirect
    ports:
      - 4040
    depends_on:
      - app-dev
    external_links:
      - nginx-proxy
    restart: unless-stopped
    network_mode: bridge

  app-dev:
    image: ${APP_DEV_IMAGE:-python:3.6}
    working_dir: /opt/app
    command: sh run-dev.sh
    volumes:
      - .:/opt/app
    environment:
      VIRTUAL_HOST: ${APP_DEV_VIRTUAL_HOST:-dev.dev-docs.teracy.dev, ~^dev.dev-docs\..*\.xip\.io}
      HTTPS_METHOD: noredirect # support both http and https
    ports:
      - 80
    restart: unless-stopped
    network_mode: bridge
