name: CI

on: [push]

jobs:

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
